version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Strong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PersonasDB;User Id=SA;Password=Strong@Passw0rd;
    depends_on:
      - sqlserver
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
